### ISSUE TITLE
Configuration not parsed for intellisense

### ISSUE THREAD

**Issue by kulhanek-CNGROUP** [microsoft/vscode-makefile-tools#561]
Hello,

I have a project created in [CrossStudio for ARM](https://www.rowley.co.uk/crossworks/Downloads.htm). They offer a feature to generate a makefile, which I am trying to use to build the project in VS Code. The generated makefile has to be slightly modified to work, but I managed to build it using the makefile-tools extension.

The issue I am experiencing is with Intellisense not getting proper configuration from makefile-tools extension and so the code highlighting and references are messed up.

![image](https://github.com/microsoft/vscode-makefile-tools/assets/104621353/e27952b8-cf29-4dff-81a5-fee6e595591b)

I have created [this sample repo](https://github.com/kulhanek-CNGROUP/make-test) where the problem can be reproduced. To test it, it would be necessary to install the [CrossStudio for ARM](https://www.rowley.co.uk/crossworks/Downloads.htm) - the evaluation version is enough to test it. Also the paths in the makefile should be adjusted or the makefile regenerated in CrossStudio.

I also attach 
[configurationCache.log](https://github.com/microsoft/vscode-makefile-tools/files/14298398/configurationCache.log)
[dryrun.log](https://github.com/microsoft/vscode-makefile-tools/files/14309312/dryrun.log)
[targets.log](https://github.com/microsoft/vscode-makefile-tools/files/14298400/targets.log)
for the project in VS code.

I would be very grateful for any help on this.

**Comment by gcampbell-msft** [comment]
@kulhanek-CNGROUP Thanks for this information and for posting the bug. In order for me to help investigate this, could you give the additional information of what OS you are working on? 

Thanks,

**Comment by kulhanek-CNGROUP** [comment]
@gcampbell-msft sure
Edition	Windows 10 Enterprise
Version	22H2
OS build	19045.4046
Experience	Windows Feature Experience Pack 1000.19053.1000.0

**Comment by Yingzi1234** [comment]
@gcampbell-msft Okay, we're trying to reproduce the user's question.
@kulhanek-CNGROUP We are trying to reproduce your issue, the repo we opened after cloning it according to the [repo](https://github.com/kulhanek-CNGROUP/make-test) you gave us had the error reported inside the main.c file. The error message says that the '`debugio.h`' file was not found, and we really didn't find the '`debugio.h`' file inside the **'make-test'** folder we already downloaded, could you provide us with a new reproducible file? And we notice that the error slash in the image you provided above does not appear in the second line of code.

Please feel free if you have any doubt!
![561](https://github.com/microsoft/vscode-makefile-tools/assets/101234795/e67ca498-0fad-49ee-9619-1a429a94e731)

**Comment by kulhanek-CNGROUP** [comment]
@gcampbell-msft 
Hello,
as I mentioned earlier, it is necessary that you install at least the evaluation/trial version of  [CrossStudio for ARM](https://www.rowley.co.uk/crossworks/Downloads.htm). The file in question is provided by that platform. With common installation the file should be located at (C:/Program Files/Rowley Associates Limited/CrossWorks for ARM 4.10/include). This should be recognized from the makefile as one of the include paths - see line 6 in the makefile.

What troubles me more is that none of the configuration is being parsed from the makefile.
In the configuration cache there is nothing :/
customConfigurationProvider":{"workspaceBrowse":{"browsePath":[],"compilerArgs":[]},"fileIndex":[]}}

**Comment by kulhanek-CNGROUP** [comment]
Also if installing that is an issue then feel free to just remove it from there along with the contents of the main. I don't really care about that, what I care is that none of the defines, include paths or anything gets parsed from that makefile for the configuration provides for intellisense..

**Comment by Yingzi1234** [comment]
@gcampbell-msft @kulhanek-CNGROUP This issue is not reproduced in the latest version, you can get the details below.

**ENV:**
VScode: 1.89.1
Makefile tools: 
C/C++: 1.20.5

**Repro steps:**
1. Open VSCode and clone this repo(https://github.com/kulhanek-CNGROUP/make-test.git)
2. Open main.cpp file 
3. Place the cursor on #include `“test_lib.h”` and press the shortcut key Ctrl (or Cmd) + Click

**Actual result:**
The intellisence definition is normal it can jump to the test_lib.h file
![issue561](https://github.com/microsoft/vscode-makefile-tools/assets/101234795/0247f702-a65a-4e1a-9bae-4a0376a4c2db)

**Comment by kulhanek-CNGROUP** [comment]
@Yingzi1234 @gcampbell-msft 

I pushed a new commit in that repo adding a define to illustrate the issue. Please confirm it is working or not working for you. Could I have something misconfigured?

Here's what it does on my side.

![make-test-1717583931069](https://github.com/microsoft/vscode-makefile-tools/assets/104621353/7ee581dd-491e-4184-9fda-987f59d04b8d)

**Comment by Yingzi1234** [comment]
@gcampbell-msft @kulhanek-CNGROUP Thank you for your update! we were also able to reproduce your issue in the latest version. Details are as follows.

**ENV:**
1. VSCode: 1.89.1
2. Makefile tools: v0.10.9(Pre-release)
3. C/C++: v1.20.5

**More info:**
No installation CrossStudio for ARM.

**Repro steps:**
1. Open VSCode and clone this repo(https://github.com/kulhanek-CNGROUP/make-test.git)
2. Open main.cpp file
3. Place the cursor on #include “test_lib.h” and press the shortcut key Ctrl (or Cmd) + Click
4. Place the cursor on code “test_lib.h” and click the right mouse button to select “Go to Declaration”.

**Actual result:**
The intellisence declaration shows “No declaration for ‘test_lib’” but “Go to definition” is works  (You can get the screenshot from attachment)
![new561](https://github.com/microsoft/vscode-makefile-tools/assets/101234795/582559cf-708e-482c-a6a8-c1252ebea18c)

**Comment by kulhanek-CNGROUP** [comment]
> **Actual result:**
> The intellisence declaration shows “No declaration for ‘test_lib’” but “Go to definition” is works (You can get the screenshot from attachment)

@gcampbell-msft @Yingzi1234 Also, could you please address the issue why the body of `#ifdef TEST` appears as if `TEST` is not defined? The define is located in the makefile (`-DTEST`) as shown in my previous post.

**Comment by Yingzi1234** [comment]
@kulhanek-CNGROUP Thank you for your reply, our development team is still investigating this issue and will get back to you if we have any updates. Thank you for your support!

**Comment by gcampbell-msft** [comment]
@kulhanek-CNGROUP Just following up with a small status update. I was able to grab a small amount of time to investigate this this morning, and the repro git repository doesn't seem to work for even older version of the extension, so I don't believe it ever had correct IntelliSense for this repro. 

This is obviously still a problem that we'd like to investigate, but I just wanted to follow up that it may take more time to investigate, because it's a long standing issue that may require a more complex investigation/fix. 

Thank you for your patience!

**Comment by kulhanek-CNGROUP** [comment]
@gcampbell-msft Thanks for the update, will wait patiently for any progress :)

**Comment by snehara99** [comment]
@kulhanek-CNGROUP We were not able to reproduce the issue where you couldn't go to definition of "stdint.h". Is that still reproducing for you on the lastest Makefile Tools release? We also believe that it is expected behavior that "go to declaration" is not working but "go to definition is".

However, we were able to reproduce the issue of `-DTEST` not being defined and we are actively investigating it. We will follow up soon with updates.

**Comment by snehara99** [comment]
@kulhanek-CNGROUP Thank you for your patience, we have a solution to your question. The reason why the body of `#ifdef TEST` appears as if `TEST` is not defined is because the compiler you set in `c_cpp_properties.json`, `cc1.exe`, isn't a commonly used compiler that Makefile Tools recognizes by default. For compilers that we do not seem to recognize by default, you need to explicitly share them with us in your `settings.json` file using the `makefile.additionalCompilerNames` setting:
```
"makefile.additionalCompilerNames": [
    "cc1"
]
```

**Comment by snehara99** [comment]
We will now close this bug since we were able to find you a solution. If you have any other questions, we ask that you please provide a smaller repro project so that we can help you faster. Thanks!

**Comment by kulhanek-CNGROUP** [comment]
Hi @snehara99,

thanks for the solution I can confirm it works! After adding the additional compiler name into settings.json it started parsing the configuration again.

I have played with it a little and already found that includes must be quoted after -I not before else the parsing is not working.
```
-I"C:/Users/jaku/AppData/Local/Rowley Associates Limited/CrossWorks for ARM/v4/packages/targets/STM32/include" -IC:/Users/jaku/Documents/make-test/lib -I"C:/Users/jaku/AppData/Local/Rowley Associates Limited/CrossWorks for ARM/v4/packages/CMSIS_5/CMSIS/Core/Include"
```
Will appear in makefile tools output as:
```
Includes: C:/Users/jaku/AppData/Local/Rowley Associates Limited/CrossWorks for ARM/v4/packages/targets/STM32/include;C:/Users/jaku/Documents/make-test/lib;C:/Users/jaku/AppData/Local/Rowley Associates Limited/CrossWorks for ARM/v4/packages/CMSIS_5/CMSIS/Core/Include
```

And so these includes are correctly parsed.

However
```
"-IC:/Users/jaku/AppData/Local/Rowley Associates Limited/CrossWorks for ARM/v4/packages/targets/STM32/include" -IC:/Users/jaku/Documents/make-test/lib "-IC:/Users/jaku/AppData/Local/Rowley Associates Limited/CrossWorks for ARM/v4/packages/CMSIS_5/CMSIS/Core/Include"
```

will appear in the makefile tools output as:
```
Includes: C:/Users/jaku/Documents/make-test/lib
```

Both versions compile just fine, however the misplaced quotation is not being interpreted by the parser.

This is just an observation to let you know.


One issue that still remains for me is that the -isystem is not being parsed correctly for some reason.
The following is a snippet from the Makefile Tools output:

```
Found compiler command: "C:/Program Files/Rowley Associates Limited/CrossWorks for ARM 4.10/gcc/arm-none-eabi/bin/cc1" -fmessage-length=0 -lang-asm -fdiagnostics-color=never -fdiagnostics-show-caret -E -march=armv6-m -mlittle-endian -mfloat-abi=soft -mthumb -mno-unaligned-access -nostdinc -isystem "C:/Program Files/Rowley Associates Limited/CrossWorks for ARM 4.10/include" -I"C:/Users/jaku/AppData/Local/Rowley Associates Limited/CrossWorks for ARM/v4/packages/targets/STM32/include" -IC:/Users/jaku/Documents/make-test/lib -I"C:/Users/jaku/AppData/Local/Rowley Associates Limited/CrossWorks for ARM/v4/packages/CMSIS_5/CMSIS/Core/Include" -D__SIZEOF_WCHAR_T=4 -D__ARM_ARCH_6M__ -D__CROSSWORKS_ARM -D__HEAP_SIZE__=128 -D__GNU_LINKER -D__CROSSWORKS_MAJOR_VERSION=4 -D__CROSSWORKS_MINOR_VERSION=10 -D__CROSSWORKS_REVISION=8 -DSTM32G071xx -D__VECTORS=\"STM32G071xx.vec\" -D__SYSTEM_STM32G0XX -D__TARGET_PROCESSOR_STM32G071CB -DDEBUG -D__THUMB -MD "C:/Users/jaku/Documents/make-test/test THUMB Debug/thumb_crt0.d" -MQ "test THUMB Debug/thumb_crt0.o" -quiet "C:/Program Files/Rowley Associates Limited/CrossWorks for ARM 4.10/source/thumb_crt0.s" -o "C:/Users/jaku/Documents/make-test/test THUMB Debug/thumb_crt0_PP.s"
Analyzing line: make: Leaving directory '/cygdrive/c/Users/jaku/Documents/make-test'
POPD command or end of MAKE -C: leaving directory c:\Users\jaku\Documents\make-test and entering directory c:\Users\jaku\Documents\make-test
Sending Workspace Browse Configuration: -----------------------------------
    Browse Path: C:/Users/jaku/AppData/Local/Rowley Associates Limited/CrossWorks for ARM/v4/packages/CMSIS_5/CMSIS/Core/Include;C:/Users/jaku/AppData/Local/Rowley Associates Limited/CrossWorks for ARM/v4/packages/targets/STM32/include;C:/Users/jaku/Documents/make-test/lib;C:\Users\jaku\Documents\make-test\src
    Standard: gnu99
    Compiler Path: C:/Program Files/Rowley Associates Limited/CrossWorks for ARM 4.10/gcc/arm-none-eabi/bin/cc1.exe
    Compiler Arguments: -fmessage-length=0;-fdiagnostics-color=never;-fdiagnostics-show-caret;-mcpu=cortex-m0plus;-mlittle-endian;-mfloat-abi=soft;-mthumb;-mno-unaligned-access;-mtp=soft;-mfp16-format=ieee;-nostdinc;-isystem;"C:/Program Files/Rowley Associates Limited/CrossWorks for ARM 4.10/include";-MD;"C:/Users/jaku/Documents/make-test/test THUMB Debug/main.d";-MQ;"test THUMB Debug/main.o";-quiet;-Wunused-variable;-Wuninitialized;-gdwarf-4;-g3;-gpubnames;-fomit-frame-pointer;-ffunction-sections;-fdata-sections;-fshort-enums;-fno-common;"C:\Users\jaku\Documents\make-test\src\main.c";-o;"C:/Users/jaku/Documents/make-test/test THUMB Debug/main.asm"
```

both in the Found compiler command and in the compiler arguments the `-isystem "C:/Program Files/Rowley Associates Limited/CrossWorks for ARM 4.10/include"` appears.

If I look into the C/C++ output I can find the following:
```
Requesting a custom configuration for: C:\USERS\JAKU\DOCUMENTS\MAKE-TEST\SRC\MAIN.C
Custom configurations received:
  uri: file:///c%3A/Users/jaku/Documents/make-test/src/main.c
  config: {
  "defines": [
    "__SIZEOF_WCHAR_T=4",
    "TEST",
    "__ARM_ARCH_6M__",
    "__CROSSWORKS_ARM",
    "__HEAP_SIZE__=128",
    "__GNU_LINKER",
    "__CROSSWORKS_MAJOR_VERSION=4",
    "__CROSSWORKS_MINOR_VERSION=10",
    "__CROSSWORKS_REVISION=8",
    "STM32G071xx",
    "__VECTORS=\\\"STM32G071xx.vec\\\"",
    "__SYSTEM_STM32G0XX",
    "__TARGET_PROCESSOR_STM32G071CB",
    "DEBUG",
    "__THUMB"
  ],
  "standard": "gnu99",
  "includePath": [
    "C:/Users/jaku/AppData/Local/Rowley Associates Limited/CrossWorks for ARM/v4/packages/targets/STM32/include",
    "C:/Users/jaku/Documents/make-test/lib",
    "C:/Users/jaku/AppData/Local/Rowley Associates Limited/CrossWorks for ARM/v4/packages/CMSIS_5/CMSIS/Core/Include"
  ],
  "forcedInclude": [],
  "compilerPath": "C:/Program Files/Rowley Associates Limited/CrossWorks for ARM 4.10/gcc/arm-none-eabi/bin/cc1.exe",
  "compilerArgs": [
    "-fmessage-length=0",
    "-fdiagnostics-color=never",
    "-fdiagnostics-show-caret",
    "-mcpu=cortex-m0plus",
    "-mlittle-endian",
    "-mfloat-abi=soft",
    "-mthumb",
    "-mno-unaligned-access",
    "-mtp=soft",
    "-mfp16-format=ieee",
    "-nostdinc",
    "-isystem",
    "\"C:/Program Files/Rowley Associates Limited/CrossWorks for ARM 4.10/include\"",
    "-MD",
    "\"C:/Users/jaku/Documents/make-test/test THUMB Debug/main.d\"",
    "-MQ",
    "\"test THUMB Debug/main.o\"",
    "-quiet",
    "-Wunused-variable",
    "-Wuninitialized",
    "-gdwarf-4",
    "-g3",
    "-gpubnames",
    "-fomit-frame-pointer",
    "-ffunction-sections",
    "-fdata-sections",
    "-fshort-enums",
    "-fno-common",
    "\"C:\\Users\\jaku\\Documents\\make-test\\src\\main.c\"",
    "-o",
    "\"C:/Users/jaku/Documents/make-test/test THUMB Debug/main.asm\""
  ]
}
```
I suspect that the issue might be cause by the formatting of `"\"C:/Program Files/Rowley Associates Limited/CrossWorks for ARM 4.10/include\""` but I have no idea if I can do something about it. Any advise on how to correct this?

**Comment by snehara99** [comment]
Thanks for confirming the solution works! 

For your observation about not parsing some includes properly, we actually have a work item that we think will fix most of these issues (see #352).

For the `-isystem` issue, try wrapping everything with quotes:
```
"-isystem C:/Program Files/Rowley Associates Limited/CrossWorks for ARM 4.10/include"
```
Does that work for you?
